/***************************************************************************************
 Script  : Synthetic data for DM_TBL_SRG_OCCURRENCES
 Domain  : CAAS Safety Regulation - mocked aviation safety occurrences
 Notes   : Single-row INSERTs (required by Azure Synapse Dedicated SQL Pool).
           Approval_Numbers reference existing AWI rows in DM_TBL_SRG_AMO_MOA.
****************************************************************************************/

INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0001','2024-09-02','Accident Investigation','Structural failure','AWI/001','SIA Engineering Company Limited','9V-SGA','WSSS','Technical','Level 1','Senior Lead 4','2025-07-31','Target 2025-07','ESOMS-2024-1001','GA231 accident investigation - structural failure detected on lower fuselage panel. Cross-referenced with SB 53-1234.','2024-09-10 14:00:00','2024-09-10 14:00:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0002','2024-06-21','Taxi Error Investigation','Excessive speed','AWI/002','ST Engineering Aerospace Services Pte Ltd','9V-STE','WSSS','Human','Level 2','Senior Lead 6','2025-03-31','Target 2025-03','ESOMS-2024-1002','Aircraft taxied at excessive speed on taxiway E; tug operator unfamiliar with latest taxi-speed limits.','2024-06-28 10:30:00','2024-06-28 10:30:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2023-0001','2023-10-28','External Damage','Hail damage','AWI/001','SIA Engineering Company Limited','9V-SGC','WSSS','Technical','Level 2','Senior Lead 1','2025-10-31','Target 2025-10','ESOMS-2023-2001','Hail damage detected on composite radome during post-storm inspection.','2023-11-05 09:15:00','2023-11-05 09:15:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2023-0002','2023-10-04','Fuel Spill','Fuel pit leak','AWI/001','SIA Engineering Company Limited',NULL,'WSSS','Technical','Level 2','Senior Lead 7','2025-06-30','Target 2025-06','ESOMS-2023-2002','Fuel pit leak at apron stand B22; environmental spill containment activated.','2023-10-10 16:45:00','2023-10-10 16:45:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0003','2024-04-12','Bird Strike','Engine intake ingestion','AWI/002','ST Engineering Aerospace Services Pte Ltd','9V-STF','WSSS','Technical','Level 3','Senior Lead 2','2024-08-31','Closed','ESOMS-2024-1003','Bird strike on No.1 engine during departure; borescope inspection cleared for return to service.','2024-04-15 11:00:00','2024-04-15 11:00:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0004','2024-07-18','Bird Strike','Windshield impact','AWI/005','Jet Aviation Singapore Pte Ltd','9V-JAS','WSSS','Technical','Level 3','Senior Lead 3','2024-10-31','Closed','ESOMS-2024-1004','Bird strike on captain windshield during approach; windshield replaced under CMM 56-20.','2024-07-22 10:30:00','2024-07-22 10:30:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2025-0001','2025-01-22','Runway Incursion','Unauthorised entry','AWI/007','Hawker Pacific Airservices Pte Ltd',NULL,'WSSS','Human','Level 2','Senior Lead 5','2025-09-30','In-progress','ESOMS-2025-0101','Ground vehicle entered active runway without ATC clearance; investigation on-going.','2025-01-25 08:45:00','2025-01-25 08:45:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0005','2024-11-10','Runway Incursion','Taxiway mis-identification','AWI/008','Singapore Technologies Aerospace (Paya Lebar)',NULL,'WSMC','Human','Level 3','Senior Lead 5','2025-02-28','Closed','ESOMS-2024-1005','Tow crew incorrectly taxied aircraft onto incorrect taxiway; no conflict, procedures reinforced.','2024-11-15 09:00:00','2024-11-15 09:00:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0006','2024-08-05','External Damage','Ground equipment contact','AWI/003','Pratt & Whitney Component Solutions (S) Pte Ltd','9V-PWC','WSSS','Process','Level 2','Senior Lead 1','2025-04-30','Target 2025-04','ESOMS-2024-1006','Belt loader contacted cargo door during loading; dent exceeds SRM limits.','2024-08-09 12:20:00','2024-08-09 12:20:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2025-0002','2025-02-14','Fuel Spill','Over-fuelling overflow','AWI/006','Bombardier Aerospace Services Singapore',NULL,'WSSS','Human','Level 3','Senior Lead 7','2025-08-31','In-progress','ESOMS-2025-0102','Minor fuel overflow during refuelling; operator failed to monitor tank capacity.','2025-02-18 15:10:00','2025-02-18 15:10:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0007','2024-03-30','Bird Strike','Multiple strikes','AWI/011','SIAEC Line Maintenance (KUL)','9M-MXA','WMKK','Technical','OBS','Senior Lead 2','2024-06-30','Closed','ESOMS-2024-1007','Multiple bird strikes on leading edge during approach to KUL; no damage after inspection.','2024-04-05 09:00:00','2024-04-05 09:00:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0008','2024-05-22','External Damage','Ground handling contact','AWI/002','ST Engineering Aerospace Services Pte Ltd','9V-STG','WSSS','Process','Level 3','Senior Lead 6','2024-09-30','Closed','ESOMS-2024-1008','Tug collided with nose gear during pushback; gear inspected per AMM 32-00.','2024-05-28 11:30:00','2024-05-28 11:30:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2025-0003','2025-03-08','Accident Investigation','Engine failure','AWI/004','Rolls-Royce Singapore Pte Ltd (Seletar)',NULL,'WSAP','Technical','Level 1','Senior Lead 4','2025-11-30','In-progress','ESOMS-2025-0103','Uncommanded engine shutdown during test-cell run; metallurgical analysis in progress.','2025-03-12 14:00:00','2025-03-12 14:00:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0009','2024-10-15','Taxi Error Investigation','Wrong turn','AWI/013','Lufthansa Technik Philippines','RP-LTP','RPLL','Human','Level 3','Senior Lead 6','2025-01-31','Closed','ESOMS-2024-1009','Aircraft turned onto wrong taxiway during morning push; low-visibility operations.','2024-10-20 10:45:00','2024-10-20 10:45:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2025-0004','2025-04-02','Bird Strike','Engine fan damage','AWI/015','Delta TechOps','N815DA','KATL','Technical','Level 2','Senior Lead 3','2025-10-31','In-progress','ESOMS-2025-0104','Bird ingestion caused fan blade damage; engine removed for shop inspection.','2025-04-06 08:00:00','2025-04-06 08:00:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0010','2024-12-11','Runway Incursion','Vehicle on active runway','AWI/020','Changi Avionics Services Pte Ltd',NULL,'WSSS','Process','Level 2','Senior Lead 5','2025-05-31','Closed','ESOMS-2024-1010','Maintenance van entered active runway; SOP gap closed with new radio procedure.','2024-12-15 13:30:00','2024-12-15 13:30:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0011','2024-02-18','External Damage','Lightning strike','AWI/001','SIA Engineering Company Limited','9V-SGE','WSSS','Technical','Level 3','Senior Lead 1','2024-07-31','Closed','ESOMS-2024-1011','Lightning strike marks on vertical stabiliser; repaired per SRM.','2024-02-22 09:30:00','2024-02-22 09:30:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0012','2024-11-25','Accident Investigation','Landing gear collapse','AWI/017','HAECO Xiamen','B-5678','ZSAM','Technical','Level 1','Senior Lead 4','2025-08-31','In-progress','ESOMS-2024-1012','Nose landing gear collapsed on taxi; investigation covers recent MLG overhaul.','2024-11-29 15:00:00','2024-11-29 15:00:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2025-0005','2025-02-28','Fuel Spill','Hydrant leak','AWI/001','SIA Engineering Company Limited',NULL,'WSSS','Technical','Level 3','Senior Lead 7','2025-07-31','In-progress','ESOMS-2025-0105','Hydrant valve leak detected during routine inspection; valve replaced.','2025-03-03 11:00:00','2025-03-03 11:00:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0013','2024-01-30','Bird Strike','Radome damage','AWI/018','Qantas Engineering Australia','VH-QPA','YSSY','Technical','OBS','Senior Lead 2','2024-05-31','Closed','ESOMS-2024-1013','Minor radome pitting from bird strike; composite repair completed.','2024-02-02 09:00:00','2024-02-02 09:00:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0014','2024-09-20','Taxi Error Investigation','Brake over-temp','AWI/002','ST Engineering Aerospace Services Pte Ltd','9V-STH','WSSS','Human','Level 3','Senior Lead 6','2025-02-28','Closed','ESOMS-2024-1014','Brake over-temperature warning after long taxi; crew training refreshed.','2024-09-25 14:15:00','2024-09-25 14:15:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2025-0006','2025-03-25','External Damage','FOD impact','AWI/030','Turbine Overhaul Services Pte Ltd','9V-TOS','WSSS','Process','Level 2','Senior Lead 1','2025-09-30','In-progress','ESOMS-2025-0106','FOD impact on lower wing skin; FOD walk routine under review.','2025-03-30 10:00:00','2025-03-30 10:00:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0015','2024-06-08','Runway Incursion','Taxi past hold point','AWI/012','SIAEC Line Maintenance (HKG)','B-KQA','VHHH','Human','Level 2','Senior Lead 5','2024-11-30','Closed','ESOMS-2024-1015','Aircraft taxied past CAT II hold point; crew briefed on low-vis procedures.','2024-06-12 10:00:00','2024-06-12 10:00:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0016','2024-07-01','Bird Strike','Lower fuselage','AWI/014','GMF AeroAsia Indonesia','PK-GMF','WIII','Technical','OBS','Senior Lead 2','2024-10-31','Closed','ESOMS-2024-1016','Bird remains found on lower fuselage post-landing; no damage.','2024-07-05 08:30:00','2024-07-05 08:30:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0017','2024-10-28','Accident Investigation','Tail strike','AWI/016','Ameco Beijing','B-2001','ZBAA','Technical','Level 1','Senior Lead 4','2025-06-30','In-progress','ESOMS-2024-1017','Tail strike during heavy-weight departure; rear pressure bulkhead inspected.','2024-11-02 09:00:00','2024-11-02 09:00:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0018','2024-04-25','Fuel Spill','Drain valve leak','AWI/005','Jet Aviation Singapore Pte Ltd','9V-JAT','WSSS','Technical','OBS','Senior Lead 7','2024-09-30','Closed','ESOMS-2024-1018','Minor fuel drip from drain valve; valve replaced under CMM 28-10.','2024-04-30 12:30:00','2024-04-30 12:30:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0019','2024-12-28','External Damage','Ice damage','AWI/038','Korean Air Maintenance & Engineering','HL7777','RKSI','Technical','Level 3','Senior Lead 1','2025-05-31','In-progress','ESOMS-2024-1019','Ice shedding from cowl caused dent on No.2 engine pylon fairing.','2025-01-03 11:15:00','2025-01-03 11:15:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2025-0007','2025-01-05','Bird Strike','Cockpit window','AWI/045','Etihad Engineering','A6-EMX','OMAA','Technical','Level 3','Senior Lead 3','2025-07-31','In-progress','ESOMS-2025-0107','Bird strike on First Officer windshield during cruise descent; inner-pane crack.','2025-01-10 13:45:00','2025-01-10 13:45:00');
INSERT INTO dbo.DM_TBL_SRG_OCCURRENCES (Occurrence_ID, Occurrence_Date, Activity_Code, Occurrence_Subtype, Approval_Number, Organisation_Name, Aircraft_Registration, Location, CE_Mapping, Finding_Level, Lead_Inspector, Target_Close_Date, Current_Status, ESOMS_Reference_No, Summary, data_last_updated, dm_refresh_date) VALUES ('OCC-2024-0020','2024-03-14','Taxi Error Investigation','Incorrect hold short','AWI/009','Airbus Asia Training Centre Pte Ltd',NULL,'WSSL','Human','Level 3','Senior Lead 6','2024-08-31','Closed','ESOMS-2024-1020','Training aircraft held short of wrong runway; instructor debrief completed.','2024-03-18 10:30:00','2024-03-18 10:30:00');
GO

SELECT COUNT(*) AS [RowCount] FROM dbo.DM_TBL_SRG_OCCURRENCES;
GO
